In [1]:
import numpy as np

# NumPy Exercises

### Exercise 1: Array Creation and Manipulation

1.1 Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [6]:
numpy_array = np.random.randint(1,20, size=(5,5))
print("Original Array",numpy_array)
numpy_array[:,2] = 1
print("Replace element of 2nd column",numpy_array)

Original Array [[ 6 17  3  1  9]
 [10  8 16  1  2]
 [ 9  2  6 16 17]
 [ 1  1 18 15 15]
 [ 5 17 16  5  4]]
Replace element of 2nd column [[ 6 17  1  1  9]
 [10  8  1  1  2]
 [ 9  2  1 16 17]
 [ 1  1  1 15 15]
 [ 5 17  1  5  4]]


1.2 Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Exercise 2: Array Indexing and Slicing

2.1: Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [13]:
array_six = np.random.randint(1,38, size=(6,6))
print("Original Array \n",array_six)

# get sub array with row
sub_array_row = array_six[3:6]
print("\n \n sub array 3 to 5 row \n",sub_array_row)

# get sub array with column
sub_array_row = array_six[:,2:5]
print("\n \n sub array 2 to 4 column \n",sub_array_row)

Original Array 
 [[24 35  1 26  5 17]
 [17 37 12 35  7 17]
 [24 17  2 13  7 29]
 [ 7  2 12 23 10 17]
 [37 12 36 25 24  1]
 [24 20 15 31 32 27]]

 
 sub array 3 to 5 row 
 [[ 7  2 12 23 10 17]
 [37 12 36 25 24  1]
 [24 20 15 31 32 27]]

 
 sub array 2 to 4 column 
 [[ 1 26  5]
 [12 35  7]
 [ 2 13  7]
 [12 23 10]
 [36 25 24]
 [15 31 32]]



2.2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [25]:
random_array = np.random.randint(1, 21 ,size=(5, 5))
print(random_array)

# get border elements
top_element = random_array[0]
print("Top Slice of Array" ,top_element)
bottom_element = random_array[-1]
print("Top Slice of Array" ,bottom_element)
left_element = random_array[:,0]
print("Top Slice of Array" ,left_element)
right_element = random_array[:,-1]
print("Top Slice of Array" , right_element)

## now concatenate these arrays
extract = np.concatenate([top_element, bottom_element, left_element[::-1], right_element[::-1]])
print("\n Border Elements", extract)

[[19 20 17 10 18]
 [14  1  8 12 17]
 [11 13 16 17 16]
 [ 3 15  9  2  3]
 [18 14  9  7  2]]
Top Slice of Array [19 20 17 10 18]
Top Slice of Array [18 14  9  7  2]
Top Slice of Array [19 14 11  3 18]
Top Slice of Array [18 17 16  3  2]

 Border Elements [19 20 17 10 18 18 14  9  7  2 18  3 11 14 19  2  3 16 17 18]


### Exercise 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [36]:
num_array1 = np.random.randint(1, 21, size=(3,4))
num_array2 = np.random.randint(1, 21, size=(3,4))

print(f"first array\n {num_array1} \nsecond array \n {num_array2}")

addition = num_array1 + num_array2
print("\nsum of two arrays \n",addition)

addition = num_array1 - num_array2
print("\nsub of two arrays \n",addition)

addition = num_array1 * num_array2
print("\nmultiply of two arrays \n",addition)

addition = num_array1 / num_array2
print("\ndivision of two arrays \n",addition)

first array
 [[20  9 18  5]
 [14 20  8  6]
 [15 13  5  1]] 
second array 
 [[ 5 15 10 17]
 [12 16 14 14]
 [13  6  8  8]]

sum of two arrays 
 [[25 24 28 22]
 [26 36 22 20]
 [28 19 13  9]]

sub of two arrays 
 [[ 15  -6   8 -12]
 [  2   4  -6  -8]
 [  2   7  -3  -7]]

multiply of two arrays 
 [[100 135 180  85]
 [168 320 112  84]
 [195  78  40   8]]

division of two arrays 
 [[4.         0.6        1.8        0.29411765]
 [1.16666667 1.25       0.57142857 0.42857143]
 [1.15384615 2.16666667 0.625      0.125     ]]



2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
num_array3 = np.random.randint(1, 16, size=(4,4))
print(num_array3)

#row wise
row_sum = num_array3.sum(axis=1)
print("\nSum of all rows\n",row_sum)

# column wise 
column_sum = num_array3.sum(axis=0)
print("\nSum of all column\n",column_sum)

[[ 4  1 10  9]
 [ 5  2 11 15]
 [10 12 12  7]
 [ 5  1 10 13]]

Sum of all rows
 [24 33 41 29]

Sum of all column
 [24 16 43 44]


### Exercise 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [41]:
num_array4 = np.random.randint(1, 21, size=(5,5))

print(num_array4)

arr_mean = np.mean(num_array4)
print("\nmean of the array: \n",arr_mean)

arr_median = np.median(num_array4)
print("\nmedian of the array: \n", arr_median)

std_value = np.std(num_array4)
print("\nstandard deviation of the array: \n", std_value)

variance = np.var(num_array4)
print("\nvariance of the array: \n", variance)




[[ 1  4  4 10  4]
 [10  9  4  2 19]
 [17  3  4  1 19]
 [12  5 16 14  3]
 [15  2 10  7 17]]

mean of the array: 
 8.48

median of the array: 
 7.0

standard deviation of the array: 
 5.953956667628679

variance of the array: 
 35.449600000000004



2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [45]:
num_array4 = np.random.randint(1, 10, size=(3,3))

print(num_array4)

# Compute mean and standard deviation
mean = np.mean(num_array4)
std = np.std(num_array4)

# Standardize the array
scaled_arr = (num_array4 - mean) / std

print("Scaled array:\n", scaled_arr)

# Verify mean and std
print("\nMean of scaled array:\n", np.mean(scaled_arr))
print("\nStd of scaled array:\n", np.std(scaled_arr))

[[2 2 5]
 [7 2 4]
 [1 7 5]]
Scaled array:
 [[-0.88618626 -0.88618626  0.52128604]
 [ 1.4596009  -0.88618626  0.0521286 ]
 [-1.35534369  1.4596009   0.52128604]]

Mean of scaled array:
 3.700743415417188e-17

Std of scaled array:
 1.0


### Exercise 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [53]:
arr1d = np.array([10, 20, 30])

# Add the 1D array to each row of the 2D array
result = num_array4 + arr1d

print("Result:\n", result)

Result:
 [[12 22 35]
 [17 22 34]
 [11 27 35]]



2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.



In [ ]:
num_array5 = np.random.randint(1, 16, size=(4,4))
print(num_array5)

arr1d = np.array([1, 2, 3, 4])
result = num_array5 - arr1d
print("\n----- Subtract ------\n")
print(result)

[[ 6 11 12 15]
 [ 8  9  6  6]
 [ 8  7  9 13]
 [ 7 14 12  8]]
----- Subtract ------
[[ 5  9  9 11]
 [ 7  7  3  2]
 [ 7  5  6  9]
 [ 6 12  9  4]]


### Exercise 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [66]:
num_array6 = np.random.randint(1, 21, size=(3, 3))
print(num_array6)

# Determinant
det = np.linalg.det(num_array6)
print("Determinant:", det)

# Inverse (only if determinant is not 0)
if det != 0:
    inv = np.linalg.inv(num_array6)
    print("Inverse:\n", inv)
else:
    print("Matrix is singular; no inverse.")

# Eigenvalues
eigenvalues = np.linalg.eigvals(num_array6)
print("Eigenvalues:", eigenvalues)

[[20 12 16]
 [ 5 19  4]
 [ 9 19  6]]
Determinant: -384.0
Inverse:
 [[-0.09895833 -0.60416667  0.66666667]
 [-0.015625    0.0625      0.        ]
 [ 0.19791667  0.70833333 -0.83333333]]
Eigenvalues: [35.20202889 10.80732895 -1.00935784]



2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [ ]:
arr1 = np.random.randint(1,20, size=(2,3))
arr2 = np.random.randint(1,20, size=(3,2))

print(arr1, "\n \n", arr2)
print("------ multiplication ------")

# arr1 @ arr2 OR np.dot 
# result = arr1 @ arr2 
result = np.dot(arr1, arr2)
print(result)

[[7 2 7]
 [3 5 9]] 
 
 [[18  5]
 [15  4]
 [ 8  1]]
------ multiplication ------
[[212  50]
 [201  44]]


### Exercise 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [73]:
arr = np.arange(1, 10).reshape(3, 3)
print("Original array:\n", arr)

# Reshape to (1, 9)
arr_row = arr.reshape(1, 9)
print("\nReshaped to (1, 9):\n", arr_row)

# Reshape to (9, 1)
arr_col = arr.reshape(9, 1)
print("\nReshaped to (9, 1):\n", arr_col)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Reshaped to (1, 9):
 [[1 2 3 4 5 6 7 8 9]]

Reshaped to (9, 1):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]



2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [79]:
arr = np.random.randint(1, 21, size=(5, 5))
print("Original array (5x5):\n", arr)

# Flatten the array to 1D
flattened = arr.flatten()
print("\nFlattened array:\n", flattened)

# Reshape back to 5x5
reshaped = flattened.reshape(5, 5)
print("\nReshaped array (5x5):\n", reshaped)

Original array (5x5):
 [[17  9 16 17 20]
 [12  8 16 19 13]
 [ 9  8  2 17  5]
 [17 16  7 19 19]
 [14  2 15  4  3]]

Flattened array:
 [17  9 16 17 20 12  8 16 19 13  9  8  2 17  5 17 16  7 19 19 14  2 15  4
  3]

Reshaped array (5x5):
 [[17  9 16 17 20]
 [12  8 16 19 13]
 [ 9  8  2 17  5]
 [17 16  7 19 19]
 [14  2 15  4  3]]


### Exercise 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [ ]:
arr = np.random.randint(1, 21, size=(5, 5))
print("Original array:\n", arr)

corner_element = arr[[0, 0, -1, -1], [0, -1, 0, -1]]
print("\ncorner element\n", corner_element)

Original array (5x5):
 [[15  9 11  1  6]
 [ 3  2  8  5 13]
 [ 9  4 16 10  6]
 [ 6 18  5  5 14]
 [ 7 11  2  4 19]]

corner element
 [15  6  7 19]



2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [99]:
arr = np.random.randint(1, 21, size=(4, 4))
print("Original array:\n", arr)

arr[arr>10] = 10

print("\nmodified array\n",arr)

Original array:
 [[17 19 14  1]
 [ 4  4 18 15]
 [ 3  7  2  5]
 [13  5 20  3]]

modified array
 [[10 10 10  1]
 [ 4  4 10 10]
 [ 3  7  2  5]
 [10  5 10  3]]


### Exercise 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [102]:
arr = np.array([
    ("Talha", 25, 72.5),
    ("Jhon", 36, 65.5),
    ("Alex", 32, 68.7),
    ("Tailor", 58, 73.7),
    ("Julia", 18, 41.4),
    ("Sam", 33, 60),
    ("Sara", 27, 71.2)
], dtype=[("name", "U10"), ("age", "i4"), ("weight", "f4")])
print("Orignal Array",arr)


sorted_people = np.sort(arr, order="age")
print("\nSorted by age:\n", sorted_people)

Orignal Array [('Talha', 25, 72.5) ('Jhon', 36, 65.5) ('Alex', 32, 68.7)
 ('Tailor', 58, 73.7) ('Julia', 18, 41.4) ('Sam', 33, 60. )
 ('Sara', 27, 71.2)]

Sorted by age:
 [('Julia', 18, 41.4) ('Talha', 25, 72.5) ('Sara', 27, 71.2)
 ('Alex', 32, 68.7) ('Sam', 33, 60. ) ('Jhon', 36, 65.5)
 ('Tailor', 58, 73.7)]



2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [105]:
points = np.array([
    (1, 2),
    (3, 4),
    (5, 6),
    (7, 8)
], dtype=[("x", "i4"), ("y", "i4")])

print("Points:\n", points)

distances_from_origin = np.sqrt(points["x"]**2 + points["y"]**2)
print("\nDistance from origin:\n", distances_from_origin)

# Extract x and y as normal arrays
coords = np.column_stack((points["x"], points["y"]))

# Compute pairwise distances
diffs = coords[:, np.newaxis, :] - coords[np.newaxis, :, :]
pairwise_distances = np.sqrt(np.sum(diffs**2, axis=-1))

print("\nPairwise distances:\n", pairwise_distances)

Points:
 [(1, 2) (3, 4) (5, 6) (7, 8)]

Distance from origin:
 [ 2.23606798  5.          7.81024968 10.63014581]

Pairwise distances:
 [[0.         2.82842712 5.65685425 8.48528137]
 [2.82842712 0.         2.82842712 5.65685425]
 [5.65685425 2.82842712 0.         2.82842712]
 [8.48528137 5.65685425 2.82842712 0.        ]]


### Exercise 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [ ]:
arr = np.random.randint(1, 21, size=(4, 4))
print("Original array:\n", arr)

# elements > 10 are masked
masked_arr = np.ma.masked_greater(arr, 10)
print("\nMasked array (elements > 10 hidden):\n", masked_arr)

# Compute sum of unmasked elements
sum_unmasked = masked_arr.sum()
print("\nSum of unmasked elements:", sum_unmasked)

Original array:
 [[20 13 14 19]
 [ 3  1 14  8]
 [ 2  1  7 15]
 [10  7  5  1]]

Masked array (elements > 10 hidden):
 [[-- -- -- --]
 [3 1 -- 8]
 [2 1 7 --]
 [10 7 5 1]]

Sum of unmasked elements: 45


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:
arr = np.random.randint(1, 21, size=(3, 3))
print("Original array:\n", arr)

# diagonal elements
masked_arr = np.ma.masked_array(arr, mask=np.eye(3, dtype=bool))
print("\nMasked array (diagonal masked):\n", masked_arr)

# Compute mean of unmasked elements
mean_unmasked = masked_arr.mean()
print("\nMean of unmasked elements:", mean_unmasked)

# Replace masked (diagonal) elements with mean
filled_arr = masked_arr.filled(mean_unmasked)
print("\nFinal array with diagonal replaced by mean:\n", filled_arr)

Original array:
 [[ 8 20  2]
 [ 8 18  9]
 [ 4  2 13]]

Masked array (diagonal masked):
 [[-- 20 2]
 [8 -- 9]
 [4 2 --]]

Mean of unmasked elements: 7.5

Final array with diagonal replaced by mean:
 [[ 7 20  2]
 [ 8  7  9]
 [ 4  2  7]]
