# NumPy Cheat Sheet for Data Analysis

In [3]:
# Import NumPy
import numpy as np

## Create Array

In [4]:
# 1. Array Creation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros((2, 3))
arr3 = np.ones((3, 3))
arr4 = np.arange(0, 10, 2)
arr5 = np.linspace(0, 1, 5)

print("Array from list:", arr1)
print("Zeros array:\n", arr2)
print("Ones array:\n", arr3)
print("Arange array:", arr4)
print("Linspace array:", arr5)

Array from list: [1 2 3 4 5]
Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arange array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


## Array Manipulation

In [5]:
# 2. Array Manipulation
arr_reshaped = arr1.reshape((5, 1))
arr_transposed = arr3.T
arr_concat = np.concatenate([arr1, arr4])
arr_split = np.array_split(arr1, 2)

print("Reshaped array:\n", arr_reshaped)
print("Transposed array:\n", arr_transposed)
print("Concatenated array:", arr_concat)
print("Split array:", arr_split)

Reshaped array:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Transposed array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Concatenated array: [1 2 3 4 5 0 2 4 6 8]
Split array: [array([1, 2, 3]), array([4, 5])]


## Mathematical Operations

In [6]:
# 3. Mathematical Operations
arr_sum = np.sum(arr1)
arr_mean = np.mean(arr1)
arr_std = np.std(arr1)
dot_product = np.dot(np.array([1, 2]), np.array([3, 4]))

print("Sum:", arr_sum)
print("Mean:", arr_mean)
print("Standard Deviation:", arr_std)
print("Dot product:", dot_product)

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
Dot product: 11


## Random Number Generation

In [7]:
# 4. Random Number Generation
rand_nums = np.random.rand(3, 3)
rand_ints = np.random.randint(1, 10, size=(2, 2))
sample = np.random.choice([10, 20, 30, 40], size=2)

print("Random numbers:\n", rand_nums)
print("Random integers:\n", rand_ints)
print("Random sample:", sample)

Random numbers:
 [[0.44129493 0.48278161 0.83186531]
 [0.52751037 0.09633166 0.60462635]
 [0.34676627 0.68474411 0.31733405]]
Random integers:
 [[5 3]
 [3 1]]
Random sample: [20 20]


## Masking and Filtering

In [8]:
# 5. Masking & Filtering
arr_masked = arr1[arr1 > 2]
print("Filtered array (elements >2):", arr_masked)

Filtered array (elements >2): [3 4 5]


## Liner Algebra

In [9]:
# 6. Linear Algebra
matrix = np.array([[1, 2], [3, 4]])
inv_matrix = np.linalg.inv(matrix)
det_matrix = np.linalg.det(matrix)

print("Inverse of matrix:\n", inv_matrix)
print("Determinant of matrix:", det_matrix)


Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of matrix: -2.0000000000000004
