## Numpy array and basics 
Learn about numpy and code 

In [6]:
import numpy as np

## create array from list

In [7]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1d array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2d array: ", arr_2d)

1d array:  [1 2 3 4 5]
2d array:  [[1 2 3]
 [4 5 6]]


## List vs numpy array

In [8]:
py_list = [1, 2, 3]
print("pyhton list miltiplication", py_list * 2)

np_array = np.array([1, 2, 3, 4])
print("Python array multiplication", np_array * 2)

import time
start = time.time()

py_list = [i*2 for i in range(10000)]
print("\n list operation time: ", time.time() -start)

start = time.time()
np_array = np.array(1000000) * 2
print("\n numpy operation time: ", time.time() - start)

pyhton list miltiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6 8]

 list operation time:  0.0010218620300292969

 numpy operation time:  0.00013065338134765625


## creating array from scratch  

In [9]:
zeros = np.zeros((3, 5))
print("zero array \n:" ,zeros)


zeros = np.zeros((3, 5))

ones = np.ones((2, 3))
print("one array: \n", ones)

zero array 
: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


## get method np.full 

In [10]:
full = np.full((1, 3), 7)
print("full array: \n ", full)

random = np.random.random([2, 3])
print("print random: \n", random)

sequence = np.arange(0, 10, 2)
print("print arange: \n", sequence)

sequence2 = np.arange(0, 10, 3)
print("print arange: \n", sequence2)

full array: 
  [[7 7 7]]
print random: 
 [[0.83338506 0.43925342 0.75097053]
 [0.65053206 0.15386942 0.1232945 ]]
print arange: 
 [0 2 4 6 8]
print arange: 
 [0 3 6 9]


## Vector, metrics and tensor

In [11]:
vector = np.array([1, 2, 3])
print("Vector: \n", vector)

matrics = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrics: \n", matrics)

tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrics: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties 

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape of array \n", arr.shape)
print("Dimention of array \n", arr.ndim)
print("Size of array \n", arr.size)
print("D-type of array \n", arr.dtype)

Shape of array 
 (2, 3)
Dimention of array 
 2
Size of array 
 6
D-type of array 
 int64


## Array Reshaping 

In [13]:
arr = np.arange(12)
print("orignal array: ", arr)

reshape = arr.reshape((4, 3))
print("Re Shaped: ", reshape)

flattened = reshape.flatten()
print("Flattened Array: \n", flattened)

#return view insted of copy
reveled = reshape.ravel()
print("\n Reveled Array \n ", reveled)

#transpose 
transpose = reshape.T
print("\n Transpaosed Array \n", transpose)

orignal array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Re Shaped:  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Flattened Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reveled Array 
  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpaosed Array 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
