## Numpy array operations

In [2]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("basic Slicing", arr[2:7])
print("with Step", arr[1:8:2])
print("negative Indexing", arr[-3])

basic Slicing [3 4 5 6 7]
with Step [2 4 6 8]
negative Indexing 8


## 2 D Array

In [7]:
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("specific Element", arr_2d[1,2])
print("entire row", arr_2d[1])
print("entire column", arr_2d[:, 1])

specific Element 6
entire row [4 5 6]
entire row [2 5 8]


## Sorting

In [15]:
unsorted_arr = np.array([3, 1, 4, 5, 1, 8])
print("Sorted Array: ", np.sort(unsorted_arr))

# 2D sorted array

unsorted_2d_arr = np.array([
    [3, 1],
    [4, 2],
    [5, 1]
])

print("Sorted 2 D array by column: \n", np.sort(unsorted_2d_arr, axis=0))
print("Sorted 2 D array by row: \n", np.sort(unsorted_2d_arr, axis=0)[:, ::-1])

Sorted Array:  [1 1 3 4 5 8]
Sorted 2 D array by column: 
 [[3 1]
 [4 1]
 [5 2]]
Sorted 2 D array by row: 
 [[1 3]
 [1 4]
 [2 5]]


## Array Filtering

In [17]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = number[number % 2 == 0]
print("Even numbers: ", even_num)

Even numbers:  [ 2  4  6  8 10]


## Filter with Mask

In [18]:
mask = number > 5
print("number grater then 5: ", number[mask])

number grater then 5:  [ 6  7  8  9 10]


## Fancy Indexing Vs np.Where

In [21]:
indices = [0, 2, 4]
print(number[indices])

where_result = np.where(number > 5)
print("np where: ", where_result)
print("np where: ", number[where_result])

[1 3 5]
np where:  (array([5, 6, 7, 8, 9]),)
np where:  [ 6  7  8  9 10]


## Condition Array

In [26]:
condition_arr = np.where(number > 5, number * 2, number)
print(condition_arr)

[ 1  2  3  4  5  6  7  8  9 10]


## Data add and Removing 

In [32]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

combined = arr1 + arr2
print("Combined 2 array: ", combined)

# Merge 2 array
merge = np.concatenate((arr1 , arr2))
print("merge 2 array: ", merge)

Combined 2 array:  [ 6  8 10 12]
merge 2 array:  [1 2 3 4 5 6 7 8]


## Array Compatibility 

In [33]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])

print("Compatiblity shape: ", a.shape == b.shape)

Compatiblity shape True


In [36]:
arr3 = np.array([[1, 2], [3, 4], [5, 6]])

new_row = np.array([7, 8])

with_new_row = np.vstack((arr3, new_row))
print(arr3)
print(new_row)

new_col = np.array([[7], [8], [9]])
with_new_col = np.hstack((arr3, new_col))
print("Add new col to arr: \n",with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[7 8]
Add new col to arr: 
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


## Delete Operation in Array

In [3]:
arr4 = np.array([1,2,3,4,5])
delete = np.delete(arr4, 2)
print("Array after deletion: ", delete)

Array after deletion:  [1 2 4 5]
